#!/bin/bash

set -ex

BASEDIR=$(dirname $0)

source "$BASEDIR/buildenv.sh"

BUILDHERE_DOCKER_RUN_ARGS=
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS -it"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS --rm"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS --init"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS --privileged"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS --ulimit nofile=65536:65536"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS --ulimit core=-1"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS --security-opt seccomp=unconfined"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS -v $HOME/.m2/repository:/root/.m2/repository"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS -v $PWD:/opt/gluten"
BUILDHERE_DOCKER_RUN_ARGS="$BUILDHERE_DOCKER_RUN_ARGS $EXTRA_DOCKER_OPTIONS"

BASH_ARGS='cd /opt/gluten && mvn clean install $GLUTEN_MAVEN_OPTIONS'

docker run $BUILDHERE_DOCKER_RUN_ARGS $DOCKER_TARGET_IMAGE_BUILDENV bash -c "$BASH_ARGS"
