FROM hongzezhang/gluten-base:latest AS gluten-tpc
MAINTAINER Hongze Zhang<hongze.zhang@intel.com>

SHELL ["/bin/bash", "-c"]

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ssh net-tools vim unzip libjemalloc-dev

ARG GLUTEN_IT_REPO
ARG GLUTEN_IT_COMMIT

RUN test -n "$GLUTEN_IT_REPO" || (echo "GLUTEN_IT_REPO not set" && false)
RUN test -n "$GLUTEN_IT_COMMIT" || (echo "GLUTEN_IT_COMMIT not set" && false)

RUN cd /opt/ \
    && git clone $GLUTEN_IT_REPO gluten-it

RUN cd /opt/gluten-it \
    && git fetch origin $GLUTEN_IT_COMMIT:build_$GLUTEN_IT_COMMIT \
    && git checkout build_$GLUTEN_IT_COMMIT
    

RUN cd /opt/gluten-it \
    && mvn clean package -Pgluten-velox -Darrow.version=10.0.0-SNAPSHOT

FROM gluten-tpc AS gluten-tpc-gdb

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gdb

FROM gluten-tpc-gdb AS gluten-tpc-gdb-server

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gdbserver

# EOF
