FROM hongzezhang/gluten-buildenv:latest AS gluten-build
MAINTAINER Hongze Zhang<hongze.zhang@intel.com>

# These branches are mainly for pre-downloading dependencies to speed-up builds. 
# Thus it should not be required to change these values every time when the build branch
# is changed.
ARG CACHE_GLUTEN_REPO
ARG CACHE_GLUTEN_BRANCH

RUN test -n "$CACHE_GLUTEN_REPO" || (echo "CACHE_GLUTEN_REPO not set" && false)
RUN test -n "$CACHE_GLUTEN_BRANCH" || (echo "CACHE_GLUTEN_BRANCH not set" && false)

RUN cd /opt/ \
    && git clone $CACHE_GLUTEN_REPO -b $CACHE_GLUTEN_BRANCH gluten

# Set ccache size
RUN ccache -M 128G
RUN ccache -s

ENV EXTRA_MAVEN_OPTIONS="-Pspark-3.2 \
                         -Pbackends-velox \
                         -Dbuild_protobuf=OFF \
                         -Dbuild_cpp=ON \
                         -Dbuild_arrow=ON \
                         -Dbuild_velox=ON \
                         -Dbuild_velox_from_source=ON \
                         -Dbuild_gazelle_cpp=OFF \
                         -DskipTests \
                         -Dscalastyle.skip=true \
                         -Dcheckstyle.skip=true \
                         -Denable_ep_cache=ON"

# Prebuild Gluten
RUN cd /opt/gluten \
    && bash -c "mvn clean install $GLUTEN_MAVEN_OPTIONS $EXTRA_MAVEN_OPTIONS"

# Build Gluten
ARG TARGET_GLUTEN_REPO
ARG TARGET_GLUTEN_COMMIT

RUN test -n "$TARGET_GLUTEN_REPO" || (echo "TARGET_GLUTEN_REPO not set" && false)
RUN test -n "$TARGET_GLUTEN_COMMIT" || (echo "TARGET_GLUTEN_COMMIT not set" && false)

RUN cd /opt/gluten \
    && git fetch $TARGET_GLUTEN_REPO $TARGET_GLUTEN_COMMIT:build_$TARGET_GLUTEN_COMMIT \
    && git checkout build_$TARGET_GLUTEN_COMMIT

RUN cd /opt/gluten \
    &&  bash -c "mvn clean install $GLUTEN_MAVEN_OPTIONS $EXTRA_MAVEN_OPTIONS"

# EOF
